[versions]
kottage = "0.9.1"
kotlin = "1.7.10"
kotlinx-coroutines = "1.6.4"
kotest = "5.4.2"
gradle-android = "7.4.0-alpha10"
gradle-android-compile-sdk = "33"
gradle-android-target-sdk = "33"
gradle-android-min-sdk = "16"
sqldelight = "1.5.3"

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-android" }
gradle-multiplatform = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-js = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.4.0" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.8.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.5.0" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.5.1" }
androidx-material = { module = "com.google.android.material:material", version = "1.6.1" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.2" }
test-kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
test-kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
test-kotest-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
test-mockk = { module = "io.mockk:mockk", version = "1.12.4" }
test-turbine = { module = "app.cash.turbine:turbine", version = "0.10.0" }
sqldelight-driver-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-driver-jvm = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-driver-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-driver-js = { module = "com.squareup.sqldelight:sqljs-driver", version.ref = "sqldelight" }
klock = { module = "com.soywiz.korlibs.klock:klock", version = "3.2.0" }
kodein-di = { module = "org.kodein.di:kodein-di", version = "7.14.0" }

[bundles]
test-common = [
    "kotlin-reflect", "kotlinx-coroutines-test", "test-kotest-engine",
    "test-kotest-assertions", "test-turbine"]

[plugins]
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization" }
kotest-multiplatform = { id = "io.kotest.multiplatform" }
compose = { id = "org.jetbrains.compose", version = "1.1.0" }
sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqldelight" }
buildlogic-android-library = { id = "build-logic.android.library" }
buildlogic-multiplatform-library = { id = "build-logic.multiplatform.library" }
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.1.0" }
