[versions]
kkvs = "0.0.1"
kotlin = "1.7.10"
kotlin-coroutines = "1.6.1"
kotest = "5.3.0"
gradle-android = "7.4.0-alpha08"
gradle-android-compile-sdk = "30"
gradle-android-target-sdk = "30"
gradle-android-min-sdk = "16"

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-android" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.3.2" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.8.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.0" }
androidx-material = { module = "com.google.android.material:material", version = "1.6.1" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.2" }
test-kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
test-kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
test-kotest-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
test-mockk = { module = "io.mockk:mockk", version = "1.12.4" }
klock = { module = "com.soywiz.korlibs.klock:klock", version = "2.7.0" }
kodein-di = { module = "org.kodein.di:kodein-di", version = "7.14.0" }
napier = { module = "io.github.aakira:napier", version = "2.6.1" }

[bundles]
test-common = [
    "kotlin-reflect", "kotlinx-coroutines-test", "test-kotest-engine",
    "test-kotest-assertions", "test-mockk"]

[plugins]
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization" }
kotest-multiplatform = { id = "io.kotest.multiplatform" }
compose = { id = "org.jetbrains.compose", version = "1.1.0" }
sqldelight = { id = "com.squareup.sqldelight", version = "1.5.3" }
buildlogic-android-library = { id = "build-logic.android.library" }
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.1.0" }
