# コミットごとに Unit Test 実行
name: Build & Test (Linux)

on: push

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: gcc:7.3
    steps:
      - name: Setup Container
        run: |
          # Kotlin/Native では古い glibc (2.19) を使用している
          # 新しすぎる glibc ではビルドができない
          # /usr/lib/x86_64-linux-gnu/libsqlite3.so: error: undefined reference to 'fcntl64', version 'GLIBC_2.28'
          # /usr/lib/x86_64-linux-gnu/libsqlite3.so: error: undefined reference to 'log', version 'GLIBC_2.29'
          # glibc 2.27 以下を使うために gcc:7.3 イメージを利用
          echo "deb [trusted=yes] http://archive.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
          sed -i -e 's/deb.debian.org/archive.debian.org/g' -e 's|security.debian.org|archive.debian.org/|g' -e '/stretch-updates/d' /etc/apt/sources.list
          apt update
          # VACUUM INTO のために sqlite 3.27 以上にアップデート
          apt-get -yt stretch-backports install libsqlite3-dev
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: ./.github/actions/gradle-cache
      - name: Linux Test Build
        run: |
          ./gradlew linkDebugTestLinuxX64
      - name: Linux Test
        run: |
          ./gradlew linuxX64Test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: "**/build/test-results/*/*.xml"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: "**/build/reports/tests/*"
  upload-test:
    runs-on: ubuntu-latest
    needs: [ build-test ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: test-results
      - uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: "**/build/test-results/*/*.xml"
          comment_mode: off
