# コミットごとに Unit Test 実行
name: Build & Test (Linux)

on: push

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: gcc:7.5
    steps:
      - name: Setup Container
        run: |
          # glibc 2.27 以下を使うために gcc:7.3 イメージを利用
          echo "deb [trusted=yes] http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
          apt update
          # VACUUM INTO のために sqlite 3.27 以上にアップデート
          apt-get -yt stretch-backports install libsqlite3-dev
      - uses: actions/checkout@v3
      - id: get-month
        run: echo "month=$(TZ=Asia/Tokyo date +%m)" >> $GITHUB_OUTPUT
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/transforms-*
            ~/.gradle/caches/modules-*
          key: gradle-dependencies-${{ steps.get-month.outputs.month }}-${{ hashFiles('gradle/libs.versions.toml', '**/*.gradle.kts', 'build-logic/**/*.{kt,kts}') }}
          restore-keys: gradle-dependencies-${{ steps.get-month.outputs.month }}-
      - uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            ~/.gradle/native
          key: ${{ runner.os }}-kotlin-native-${{ steps.get-month.outputs.month }}-${{ hashFiles('gradle/libs.versions.toml', '**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-kotlin-native-${{ steps.get-month.outputs.month }}-
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/build-cache-*
            ~/.gradle/caches/[0-9]*.*
            .gradle
          key: ${{ runner.os }}-gradle-build-${{ github.workflow }}-${{ steps.get-month.outputs.month }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle-build-${{ github.workflow }}-${{ steps.get-month.outputs.month }}-
      - name: Linux Test Build
        run: |
          ./gradlew linkDebugTestLinuxX64
      - name: Linux Test
        run: |
          ./gradlew linuxX64Test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: "**/build/test-results/*/*.xml"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: "**/build/reports/tests/*"
  upload-test:
    runs-on: ubuntu-latest
    needs: [ build-test ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: test-results
      - uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: "**/build/test-results/*/*.xml"
          comment_mode: off
